export const START_FETCHING_LISTS_EVENTCATEGORY =
  "redux/lists/START_FETCHING_LISTS_EVENTCATEGORY";
export const SUCCESS_FETCHING_LISTS_EVENTCATEGORY =
  "redux/lists/SUCCESS_FETCHING_LISTS_EVENTCATEGORY";
export const ERROR_FETCHING_LISTS_EVENTCATEGORY =
  "redux/lists/ERROR_FETCHING_LISTS_EVENTCATEGORY";

export const START_FETCHING_LISTS_VENDOR =
  "redux/lists/START_FETCHING_LISTS_VENDOR";
export const SUCCESS_FETCHING_LISTS_VENDOR =
  "redux/lists/SUCCESS_FETCHING_LISTS_VENDOR";
export const ERROR_FETCHING_LISTS_VENDOR =
  "redux/lists/ERROR_FETCHING_LISTS_VENDOR";

export const START_FETCHING_LISTS_PURPOSED_DATE =
  "redux/lists/START_FETCHING_LISTS_PURPOSED_DATE";
export const SUCCESS_FETCHING_LISTS_PURPOSED_DATE =
  "redux/lists/SUCCESS_FETCHING_LISTS_PURPOSED_DATE";
export const ERROR_FETCHING_LISTS_PURPOSED_DATE =
  "redux/lists/ERROR_FETCHING_LISTS_PURPOSED_DATE";
